### ISSUE TITLE
如果这样设置，上下滑动不了。

### ISSUE THREAD

**Issue by why168** [BCsl/UcMainPagerDemo#2]
# mNewsPager.setAdapte()

* 我在里面塞的PagerAdapter怎么就滑动不了了？

* 还有TestFragment的布局不这样写就滑动不了，怎么解决？

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/test_recycler"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </android.support.v4.widget.SwipeRefreshLayout>
</LinearLayout>
```

**Comment by why168** [comment]
@BCsl 大神解决下吧

**Comment by BCsl** [comment]
1、2两个问题不能滑动，首先确定你的控件是NestedScrollingChild的子类，具体原因看文章 @why168

**Comment by why168** [comment]
你研究过里面套用WebView，实现NestedScrollingChild接口，这么玩吗？  效果做起来跟RecyclerView一样

**Comment by why168** [comment]
找到了解决方案了，一个老外写了，针对WebView实现NestedScrollingChild接口做了处理。
[https://github.com/rhlff/NestedScrollWebView/blob/master/lib/src/main/java/com/tobiasrohloff/view/NestedScrollWebView.java](https://github.com/rhlff/NestedScrollWebView/blob/master/lib/src/main/java/com/tobiasrohloff/view/NestedScrollWebView.java)
