### ISSUE TITLE
recycleview behavior怎么控制？

### ISSUE THREAD

**Issue by xpbtmusic** [BCsl/UcMainPagerDemo#4]
你好：
    recycleview behavior怎么控制？

**Comment by xpbtmusic** [comment]
滑动到顶部，然后往下滑动再下来。不用按返回键。

**Comment by BCsl** [comment]
@xpbtmusic  RecycleView behavior 跟普通的没区别啊。如果想改成不用返回键也不是难事，主要 Demo 实现上的需求需要返回按钮
