### ISSUE TITLE
一个滑动问题

### ISSUE THREAD

**Issue by JeffZane** [BCsl/UcMainPagerDemo#7]
close状态下，向上滑动列表，按下返回键变为open状态，此时无法向下滑动列表。
向上滑动(不松手)至close状态，再向下滑动，依然可以变回open状态。
不知道有没有解决办法？

**Comment by BCsl** [comment]
解决是肯定可以的，你可以试着修复然后 pr，不然我只能有空的时候才能改

**Comment by JeffZane** [comment]
最近忙着新一轮的迭代，有空的时候我尝试一下哈

2017-08-29 18:49 GMT+08:00 HelloCsl <notifications@github.com>:
